version: '3'
services:

  knet:
    image: ketzu/knet:latest
    restart: always
    hostname: old.ketzu.net
    env_file:
      - ~/secrets/knet.env
    volumes:
      - ~/data/knet.sqlite3:/db.sqlite3
      - knet_media_storage:/media
    networks:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.knet.rule=Host(`old.ketzu.net`)"
      - "traefik.http.routers.knet.entryPoints=websecure"
      - "traefik.http.routers.knet.tls=true"
      - "traefik.http.routers.knet.tls.certresolver=le"
      
  media:
    image: nginx:latest
    restart: always
    hostname: media.ketzu.net
    volumes:
      - knet_media_storage:/usr/share/nginx/html:ro
    networks:
      web:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.knet_media.rule=Host(`media.ketzu.net`)"
      - "traefik.http.routers.knet_media.entryPoints=websecure"
      - "traefik.http.routers.knet_media.tls=true"
      - "traefik.http.routers.knet_media.tls.certresolver=le"

networks:
  web:
    external: true

volumes:
  knet_media_storage: