version: '3'

volumes:
    prometheus_data:

networks:
  web:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - "./prometheus.yml:/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    networks:
      web:
    restart: always