version: '3'

volumes:
    prometheus_data:

networks:
  back:
    external: true
  web:
    external: true

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      back:
      web:
    restart: always