version: '3'

volumes:
    prometheus_data:

networks:
  back:
    external: true

services:
  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - "./prometheus.yml:/prometheus.yml"
      - "./alert.rules:/alert.rules"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    networks:
      - back
    restart: always