version: '3'

volumes:
    prometheus_data:

networks:
  back:
    external: true

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/prometheus.yml"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      back:
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.ketzu.net`)"
      - "traefik.http.routers.prometheus.entryPoints=websecure"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.tls.certresolver=le"