version: '3'
services:

  budget:
    image: ketzu/budget:latest
    restart: always
    hostname: budget.ketzu.net
    networks:
      - mysql_net
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budget.rule=Host(`budget.ketzu.net`)"
      - "traefik.http.routers.budget.entryPoints=websecure"
      - "traefik.http.routers.budget.tls=true"
      - "traefik.http.routers.budget.tls.certresolver=le"
    environment:
      - DB_SERVER
      - DB_NAME
      - DB_USER
      - DB_PASSWORD


networks:
  web:
    external: true
  mysql_net:
    external: true
