version: '3'

services:
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      web:
    command:
      - '-docker_only=true'
      - '-housekeeping_interval=30s'
      - '-disable_metrics=disk'
    restart: always
    
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      web:
    restart: always
  
  prometheus:
    image: prom/prometheus
    volumes:
      - config:/config
      - prometheus_data:/prometheus
    command:
      - '--config.file=/config/monitoring/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      web:
    restart: always
  
  grafana:
    image: grafana/grafana
    user: "472"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      web:
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP
      - GF_INSTALL_PLUGINS

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`monitoring.ketzu.net`)"
      - "traefik.http.routers.grafana.entryPoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=le"

networks:
  web:
    external: true

volumes:
    grafana_data:
        external: true
    config:
        external: true
    prometheus_data:
        external: true
