[http.routers]
  [http.routers.redirecttohttps]
    entryPoints = ["web"]
    middlewares = ["httpsredirect"]
    rule = "HostRegexp(`{host:.+}`)"
    service = "noop"
  [http.routers.dashboard]
    rule = "Host(`traefik.iypt.org`)"
    service="api@internal"
    middlewares = ["dash-auth"]
    [http.routers.dashboard.tls]
      certresolver="le"

[tls]
  [tls.options]
    [tls.options.default]
      minVersion = "VersionTLS12"
      sniStrict = true

[http.services]
  # noop service, the URL will be never called
  [http.services.noop.loadBalancer]
    [[http.services.noop.loadBalancer.servers]]
      url = ""

[http.middlewares]
  [http.middlewares.httpsredirect.redirectScheme]
    scheme = "https"

  [http.middlewares.security-headers.headers]
      # CORS
      #AccessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
      #AccessControlAllowOrigin = "origin-list-or-null"
      #AccessControlMaxAge = 100
      #AddVaryHeader = true
      #BrowserXssFilter = true
      ContentTypeNosniff = true
      ForceSTSHeader = true
      #FrameDeny = true
      SSLRedirect = true
      STSIncludeSubdomains = true
      #STSPreload = true
      #ContentSecurityPolicy = "default-src 'self' 'unsafe-inline'"
      CustomFrameOptionsValue = "SAMEORIGIN"
      #ReferrerPolicy = "same-origin"
      #FeaturePolicy = "vibrate 'self'"
      STSSeconds = 31536000
