version: '3'

services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      #- LOG_LEVEL=debug
      - SELF_UPDATE=true
      #- IGNORE=mongo influxdb postgres mariadb
      - TZ=Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
