version: '3.8'

services:

  recsuwp:
    build: ../wordpress
    image: wp_base
    restart: always
    hostname: www.recsu.de
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes:
      - recsu_wp:/var/www/html
      - config:/usr/local/etc/php/conf.d/config:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recsuwp.rule=Host(`www.recsu.de`, `recsu.de`)"
      - "traefik.http.routers.recsuwp.entryPoints=websecure"
      - "traefik.http.routers.recsuwp.tls=true"
      - "traefik.http.routers.recsuwp.tls.certresolver=le"

#  resuapi: Coming Soon
#  recsuapp: Coming Soon

networks:
  web:
    external: true
  mysql_net:
    external: true

volumes:
  recsu_wp:
    external: true
  config:
    external: true