version: '3.1'

services:

  recsuwp:
    image: wordpress
    restart: always
    hostname: www.recsu.de
    env_file:
      - ~/secrets/recsu_wp.env
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    volumes:
      - recsu_wp:/var/www/html
      - ../helpers/docker-uploads.ini:/usr/local/etc/php/conf.d/docker-uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.recsuwp.rule=Host(`www.recsu.de`, `recsu.de`)"
      - "traefik.http.routers.recsuwp.entryPoints=websecure"
      - "traefik.http.routers.recsuwp.tls=true"
      - "traefik.http.routers.recsuwp.tls.certresolver=le"

#  resuapi: Coming Soon
#  recsuapp: Coming Soon

networks:
  web:
    external: true
  mysql_net:
    external: true

volumes:
  recsu_wp:
    external: true