version: '3'
services:

  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    hostname: mysql.ketzu.net
    networks:
      - mysql_net
    volumes:
      - mysql_storage:/var/lib/mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mysql.rule=Host(`mysql.ketzu.net`)"
      - "traefik.http.routers.mysql.entryPoints=websecure"
      - "traefik.http.routers.mysql.tls=true"
      - "traefik.http.routers.mysql.tls.certresolver=le"

  adminer:
    image: adminer
    restart: always
    networks:
      - web
      - mysql_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.ketzu.net`)"
      - "traefik.http.routers.adminer.entryPoints=websecure"
      - "traefik.http.routers.adminer.tls=true"
      - "traefik.http.routers.adminer.tls.certresolver=le"


volumes:
  mysql_storage:
    external: true

networks:
  web:
    external: true
  mysql_net:
    external: true