version: '3.1'

services:

  knetwp:
    image: wordpress
    restart: always
    hostname: www.ketzu.net
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    volumes:
      - knet_wp:/var/www/html
      - ../helpers/docker-uploads.ini:/usr/local/etc/php/conf.d/docker-uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ketzuwp.rule=Host(`www.ketzu.net`,`ketzu.net`)"
      - "traefik.http.routers.ketzuwp.entryPoints=websecure"
      - "traefik.http.routers.ketzuwp.tls=true"
      - "traefik.http.routers.ketzuwp.tls.certresolver=le"

networks:
  web:
    external: true
  mysql_net:
    external: true

volumes:
  knet_wp:
    external: true