version: '3.1'

services:

  knetwp:
    build: ../wordpress
    image: wp_base
    restart: always
    hostname: www.ketzu.net
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    volumes:
      - knet_wp:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ketzuwp.rule=Host(`www.ketzu.net`,`ketzu.net`)"
      - "traefik.http.routers.ketzuwp.entryPoints=websecure"
      - "traefik.http.routers.ketzuwp.tls=true"
      - "traefik.http.routers.ketzuwp.tls.certresolver=le"

networks:
  web:
    external: true
  mysql_net:
    external: true

volumes:
  knet_wp:
    external: true