version: '3.1'

services:

  knetwp:
    image: wordpress
    restart: always
    hostname: wp.ketzu.net
    env_file:
      - ~/secrets/knet_wp.env
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    volumes:
      - knet_wp:/var/www/html
      - knet_media_storage:/media
      - ../helpers/docker-uploads.ini:/usr/local/etc/php/conf.d/docker-uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ketzuwp.rule=Host(`wp.ketzu.net`)"
      - "traefik.http.routers.ketzuwp.entryPoints=websecure"
      - "traefik.http.routers.ketzuwp.tls=true"
      - "traefik.http.routers.ketzuwp.tls.certresolver=le"


networks:
  web:
    external: true
  mysql_net:
    external: true

volumes:
  knet_media_storage:
    external: true
  knet_wp:
    external: true