version: '3.1'

services:

  shittyidle:
    image: wordpress
    restart: always
    hostname: www.shittyidle.com
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      - web
      - mysql_net
    volumes:
      - shittyidle_wp:/var/www/html
      - ../helpers/docker-uploads.ini:/usr/local/etc/php/conf.d/docker-uploads.ini
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shittyidle.rule=Host(`www.shittyidle.com`,`shittyidle.com`)"
      - "traefik.http.routers.shittyidle.entryPoints=websecure"
      - "traefik.http.routers.shittyidle.tls=true"
      - "traefik.http.routers.shittyidle.tls.certresolver=le"

volumes:
  shittyidle_wp:
    external: true

networks:
  web:
    external: true
  mysql_net:
    external: true