version: '3.1'

services:

  shittyidle:
    image: wordpress
    restart: always
    hostname: www.shittyidle.com
    ports:
      - 8080:80
    env_file:
      - ~/secrets/shittyidle.env
    environment:
      WORDPRESS_DB_HOST: mysql
    networks:
      web:
    volumes:
      - shittyidle:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shittyidle.rule=Host(`www.shittyidle.com`)"
      - "traefik.http.routers.shittyidle.entryPoints=websecure"
      - "traefik.http.routers.shittyidle.tls=true"
      - "traefik.http.routers.shittyidle.tls.certresolver=le"

volumes:
  shittyidle:

networks:
  web:
    external: true